import fs from 'node:fs/promises';
import path from 'node:path';
import { marked } from 'marked';

const PROJECT_ROOT = process.cwd();
const CONTENT_DIR = path.join(PROJECT_ROOT, 'content');
const OUTPUT_FILE = path.join(PROJECT_ROOT, 'src/generated/content.ts');

function parseFrontMatter(raw) {
  if (!raw.startsWith('---')) return { data: {}, body: raw };
  const end = raw.indexOf('\n---', 3);
  if (end === -1) return { data: {}, body: raw };
  const header = raw.slice(3, end).trim();
  const body = raw.slice(end + 4).replace(/^\r?\n/, '');
  const data = {};
  for (const line of header.split(/\r?\n/)) {
    const idx = line.indexOf(':');
    if (idx === -1) continue;
    const key = line.slice(0, idx).trim();
    let value = line.slice(idx + 1).trim();
    // Strip a single layer of surrounding double or single quotes so authors
    // can wrap titles/descriptions that contain colons or leading whitespace.
    if (
      value.length >= 2 &&
      ((value.startsWith('"') && value.endsWith('"')) ||
        (value.startsWith("'") && value.endsWith("'")))
    ) {
      value = value.slice(1, -1);
    }
    if (key) data[key] = value;
  }
  return { data, body };
}

function parseFileName(fileName) {
  const base = fileName.replace(/\.md$/, '');
  const lastDot = base.lastIndexOf('.');
  if (lastDot === -1) return null;
  const slug = base.slice(0, lastDot);
  const lang = base.slice(lastDot + 1);
  if (!slug || !lang) return null;
  return { slug, lang };
}

async function* walkSections() {
  let appEntries;
  try {
    appEntries = await fs.readdir(CONTENT_DIR, { withFileTypes: true });
  } catch {
    return;
  }
  for (const appEntry of appEntries) {
    if (!appEntry.isDirectory()) continue;
    const appDir = path.join(CONTENT_DIR, appEntry.name);
    let sectionEntries;
    try {
      sectionEntries = await fs.readdir(appDir, { withFileTypes: true });
    } catch {
      continue;
    }
    for (const sectionEntry of sectionEntries) {
      if (!sectionEntry.isDirectory()) continue;
      yield { appId: appEntry.name, section: sectionEntry.name, dir: path.join(appDir, sectionEntry.name) };
    }
  }
}

async function readArticle({ appId, section, file }) {
  const parsed = parseFileName(file);
  if (!parsed) return null;
  const raw = await fs.readFile(path.join(CONTENT_DIR, appId, section, file), 'utf8');
  const { data, body } = parseFrontMatter(raw);
  const html = marked.parse(body, { async: false });
  return {
    slug: data.slug ?? parsed.slug,
    lang: data.lang ?? parsed.lang,
    title: data.title ?? parsed.slug,
    description: data.description ?? '',
    date: data.date ?? '',
    html,
  };
}

async function collect() {
  const articles = [];
  for await (const loc of walkSections()) {
    let files;
    try {
      files = await fs.readdir(loc.dir);
    } catch {
      continue;
    }
    for (const file of files) {
      if (!file.endsWith('.md')) continue;
      const article = await readArticle({ appId: loc.appId, section: loc.section, file });
      if (!article) continue;
      articles.push({ appId: loc.appId, section: loc.section, ...article });
    }
  }
  // Stable ordering so generated file diffs predictably.
  articles.sort((a, b) => {
    if (a.appId !== b.appId) return a.appId.localeCompare(b.appId);
    if (a.section !== b.section) return a.section.localeCompare(b.section);
    if (a.lang !== b.lang) return a.lang.localeCompare(b.lang);
    return a.slug.localeCompare(b.slug);
  });
  return articles;
}

function renderArticleLiteral(a) {
  return `  {
    appId: ${JSON.stringify(a.appId)},
    article: {
      section: ${JSON.stringify(a.section)},
      slug: ${JSON.stringify(a.slug)},
      lang: ${JSON.stringify(a.lang)},
      title: ${JSON.stringify(a.title)},
      description: ${JSON.stringify(a.description)},
      date: ${JSON.stringify(a.date)},
      html: ${JSON.stringify(a.html)},
    },
  },`;
}

function renderOutput(articles) {
  const entryLines = articles.map(renderArticleLiteral).join('\n');
  const header = `// AUTO-GENERATED by scripts/build-content.mjs - do not edit by hand.
// Source: content/{appId}/{section}/{slug}.{lang}.md

export interface ContentArticle {
  section: string;
  slug: string;
  lang: string;
  title: string;
  description: string;
  date: string;
  html: string;
}

export interface ContentEntry {
  appId: string;
  article: ContentArticle;
}

export const contentEntries: ContentEntry[] = [
${entryLines}
];

export function getContent(appId: string, section: string, lang: string, slug = 'index'): ContentArticle | undefined {
  const direct = contentEntries.find(
    (e) => e.appId === appId && e.article.section === section && e.article.lang === lang && e.article.slug === slug,
  )?.article;
  if (direct) return direct;
  // Fall back to English when a translation is missing, so every locale
  // still surfaces the full content set instead of an empty section.
  if (lang !== 'en') {
    return contentEntries.find(
      (e) => e.appId === appId && e.article.section === section && e.article.lang === 'en' && e.article.slug === slug,
    )?.article;
  }
  return undefined;
}

export function hasContent(appId: string, section: string, lang?: string): boolean {
  return contentEntries.some(
    (e) => e.appId === appId
      && e.article.section === section
      && (lang === undefined || e.article.lang === lang),
  );
}

export function listContentLangs(appId: string, section: string): string[] {
  const langs = new Set<string>();
  for (const e of contentEntries) {
    if (e.appId === appId && e.article.section === section) langs.add(e.article.lang);
  }
  return Array.from(langs);
}

export interface ContentSummary {
  slug: string;
  lang: string;
  title: string;
  description: string;
  date: string;
}

// List slugs available in a given (appId, section, lang), excluding 'index'.
// For each slug, prefers the requested locale; falls back to English when a
// translation is missing so every language still shows the full blog index.
export function listContentSlugs(appId: string, section: string, lang: string): ContentSummary[] {
  const bySlug = new Map<string, ContentSummary>();
  const collect = (locale: string) => {
    for (const e of contentEntries) {
      if (
        e.appId === appId &&
        e.article.section === section &&
        e.article.lang === locale &&
        e.article.slug !== 'index'
      ) {
        if (!bySlug.has(e.article.slug)) {
          bySlug.set(e.article.slug, {
            slug: e.article.slug,
            lang: e.article.lang,
            title: e.article.title,
            description: e.article.description,
            date: e.article.date,
          });
        }
      }
    }
  };
  collect(lang);
  if (lang !== 'en') collect('en');
  const out = Array.from(bySlug.values());
  out.sort((a, b) => (a.date < b.date ? 1 : a.date > b.date ? -1 : a.slug.localeCompare(b.slug)));
  return out;
}

// Return true when any non-'index' content exists for (appId, section) in lang
// or in English when the requested locale has none.
export function hasMultiContent(appId: string, section: string, lang: string): boolean {
  const locales = lang === 'en' ? ['en'] : [lang, 'en'];
  for (const locale of locales) {
    for (const e of contentEntries) {
      if (
        e.appId === appId &&
        e.article.section === section &&
        e.article.lang === locale &&
        e.article.slug !== 'index'
      ) return true;
    }
  }
  return false;
}
`;
  return header;
}

async function main() {
  const articles = await collect();
  const output = renderOutput(articles);
  await fs.mkdir(path.dirname(OUTPUT_FILE), { recursive: true });
  await fs.writeFile(OUTPUT_FILE, output, 'utf8');
  console.log(`[content] built ${articles.length} articles -> ${path.relative(PROJECT_ROOT, OUTPUT_FILE)}`);
}

main().catch((err) => {
  console.error('[content] build failed:', err);
  process.exitCode = 1;
});